//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputerShop_final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoProduct()
        {
            this.carts = new HashSet<cart>();
            this.Images = new HashSet<Image>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Price { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public Nullable<int> idProductType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
